# ==========================================
# NexusProject 메인 설정 파일
# ==========================================

# 데이터베이스 (MariaDB) 연결 정보
database:
  host: "127.0.0.1"
  port: 3306
  name: "minecraft_server" # 미리 생성해둔 DB 이름
  user: "root"
  password: "rladudwo7@" # DB 비밀번호를 입력하세요

# 서버 기본 설정 (예시)
settings:
  debug_mode: true
# 공성전 설정
siege:
  core-hp: 2000.0 # 코어의 최대 체력을 설정합니다. (다이아검 기준 1대에 약 7~8 데미지)
# ==========================================
# 타운(개인 영지) 시스템 설정
# ==========================================
town:
  # 스폰(0,0)에서 몇 블록 이상 떨어져야 생성 가능한지
  min-distance-from-spawn: 500
  # 다른 사람의 타운과 최소 몇 청크 떨어져야 하는지
  chunk-buffer: 10
  # 최대 소유 가능 청크 수
  max-chunks: 25
  # 청크 확장 가격 설정
  price:
    base: 2000.0             # 첫 확장 비용
    increase-per-chunk: 2000.0 # 확장할 때마다 추가로 붙는 비용 (ex: 1만 -> 1.5만 -> 2만)