name: NexusProject
version: 1.0
main: main_plugin.NexusCore
api-version: '1.21'

# [의존성 설정]
depend: [Vault, Citizens]

commands:
  포인트:
    description: "디스코드 활동 포인트로 이용하는 조공 상점을 엽니다."
    usage: /포인트
    aliases: [point, dp]
    
  money:
    description: "관리자 전용 서버 경제(돈) 관리 명령어입니다."
    usage: /money <확인/지급/차감/설정> <유저> [금액]
    permission: nexus.admin.money
    permission-message: "&c이 명령어를 사용할 권한이 없습니다."

  nexus:
    description: "넥서스 프로젝트 메인 관리 명령어입니다."
    usage: /nexus reload
    permission: nexus.admin
    permission-message: "&c플러그인 관리 권한이 없습니다."

permissions:
  nexus.admin:
    description: "플러그인 리로드 등 전체 관리 권한입니다."
    default: op
  nexus.admin.money:
    description: "서버 경제 시스템을 관리할 수 있는 권한입니다."
    default: op